language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-15
    - ANDROID_ABI=armeabi-v7a
android:
  components:
      - tools
      - platform-tools
      - tools
script:
  - ./gradlew test
after_success:
  - bash <(curl -s https://codecov.io/bash)